server.port: 8098

spring:
  main.web-application-type: reactive
  r2dbc:
    url: r2dbc:mysql://localhost:3306/spring_investing
    username: root
    password: qwerQWER1234!
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
    url: jdbc:mysql://localhost:3306/spring_investing
    user: root
    password: qwerQWER1234!
logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    web: DEBUG
