spring:
  r2dbc:
    url: r2dbc:h2:mem:///~/db/testdb;MODE=MYSQL
    username: sa
    password:
  liquibase:
    url: jdbc:h2:mem:~/db/testdb;DB_CLOSE_DELAY=-1
    user: sa
    password:
    enabled: true
